### ISSUE TITLE
Apollo Integration

### ISSUE THREAD

**Issue by TheRickTM** [erikreedstrom/MVReact#1]
In all your free time, could you implement Apollo here. Feels like it could be a bit weird to add. This seems like the best route from what I have seen for this use case:
Query: https://www.apollographql.com/docs/react/essentials/queries#manual-query
Mutation: https://www.apollographql.com/docs/react/essentials/mutations#api

Another thing we need to consider is the loading states for data vs mutations.

**Comment by erikreedstrom** [comment]
Yes, it’s a bit hard to see the external service layer with out Apollo queries or mutations being made.

I have a branch I’ll push soon that has external calls from the controller.

It actually fits nicely, as the observable query works together with `useEffect`.

**Comment by erikreedstrom** [comment]
Slightly more verbose to wire up, but the separation of concerns is well worth it.

**Comment by erikreedstrom** [comment]
Loading state is just another aspect of the view model; and can be set prior to any external call.

**Comment by TheRickTM** [comment]
Let me know when you push the branch

**Comment by erikreedstrom** [comment]
This has been integrated.
